# Generated by Django 4.0.1 on 2022-04-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('address1', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address2', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address3', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('otp', models.IntegerField(default=0)),
                ('pin', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
