# Generated by Django 4.0.1 on 2022-04-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('mobile', models.CharField(default='', max_length=12, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
